### ISSUE TITLE
Launch Escape System with integrated solid-fuel RCS thruster

### ISSUE THREAD

**Issue by sumghai** [sumghai/SDHI_ServiceModuleSystem#51]
Most users of SDHI SMS use the KSPX LES, as the stock LES has off-centered thrust and does not have sufficient power to lift the pod high enough for parachute deployment.

Perhaps it's time to make a custom LES part for inclusion in the SMS pack.

In addition to powering the main abort motors, the same solid fuel slug could be used by a set of integrated RCS thrusters built into the LES, to allow mid-abort steering. Ideally, the LES RCS should only be activated during abort, so that if the user leaves RCS on at launch, they're not accidentally using up the solid fuel reserves for no good reason.

**TODO:**
 - [x] Add four more rcsTransforms for steering in the diagonal direction
 - [x] Update sound and visual effects
  - [x] Main LES motor
  - [x] ~~Pitch control RCS motor~~ *RCS won't be able to use EFFECTS nodes until KSP 1.1*
 - [x] ~~Prevent pitch control RCS motor from consuming SolidFuel from outside the LES e.g. the Boost Protect Cover's own reserves (apparently, simply setting resourceFlowMode = NONE causes the game to hang on loading the LES part)~~ *Creating a seperate SolidFuel resource for the steering motor is the best option, so that it doesn't use the same reserves as the main LES motors*
 - [x] Refine model
 - [x] Refine textures

**Comment by sumghai** [comment]
KSP 1.0.5 now allows RCS thrusters to be toggled in the VAB/SPH editor scene, so that may help ensure that the LES RCS thrusters are only activated on abort.

I'll need to assess this myself in-game, however.

**Comment by sumghai** [comment]
Put together a crude prototype LES with four thrustTransforms and four rcsTransforms, along with the corresponding ModuleEngines and ModuleRCS respectively.

The RCS thruster needs to be manually deactivated in the VAB so that they would not start burning SolidFuel while on the pad with the RCS action group activated; however, the thrusters can be re-enabled via the Abort action group.

A quick test with the prototype gave promising results - the integrated RCS did consume the main LES SolidFuel reserve while the pod/LES combo was steered in mid-air during abort.

Updated OP with TODO list.

**Comment by sumghai** [comment]
I think this is good to go.
