### ISSUE TITLE
Fix colliders for SMS parts in KSP 1.0.5

### ISSUE THREAD

**Issue by sumghai** [sumghai/SDHI_ServiceModuleSystem#66]
While testing SDHI SMS 3.0.1 on a stock install with minimal dependencies (AnimatedDecouplers, RealChutes and MM), it was noted that when the Boost Protect Cover (BPC) and side fairings were jettisoned, they fall through some parts while intersecting/snagging with others.

Possibly requires several segments of non-concave colliders, similar to that outlined in [this tutorial for making fairing colliders convex in preparation for 1.1's changes](http://forum.kerbalspaceprogram.com/index.php?/topic/125992-tutorial-fairing-colliders/).

**TODO:**
 - [x] Test new AnimatedDecouplers DLL provided by @Kerbas-ad-astra 
 - [x] Rework BPC colliders
  - [x] Change colliders to convex meshes
  - [x] Test clipping / collision with Mk1-2 Pod and docking port
  - [x] Test aero occlusion with Mk1-2 Pod and docking port
 - [x] Rework Service Module colliders
  - [x] Change colliders to convex meshes
  - [x] Test clipping / collision with Solar PV arrays and RCS as well as Mk1-2 Pod and heatshield
 - [x] Rework Avionics Ring colliders
  - [x] Change colliders to convex meshes
  - [x] Test clipping / collision with Mk1-2 Pod and heatshield
 - [x] Rework Side Fairing colliders
  - [x] Change colliders to convex meshes
  - [x] Test clipping / collision with Service Module, Adapter, Solar PV arrays and RCS
  - [x] Test aero occlusion with Service Module, Adapter, Solar PV arrays and RCS

**Comment by Kerbas-ad-astra** [comment]
Bear in mind that AD 1.2.1 produces NullReferenceExceptions on parts that don't pass an animationName to the module -- I've made and PRed a fix at Starwaster/AnimatedDecouplers/#3, and I'm happy to toss you a compiled DLL if you can't compile it yourself.  (This fix doesn't touch the animation issue that Starwaster is working on.)  Those NREs seem to cause issues with collision (fairings falling through parts) and staging (LES towers and integrated SRBs not firing, as you're seeing in #67), and my fix repairs both.

That said, it probably would be good for the colliders to get attention, since KSP 1.0.5 is redefining all colliders to be convex (in preparation for Unity 5 in 1.1, which does not support concave colliders on rigid bodies).  I noticed that, when testing your BPC, it seemed to "rip off" the solar panels (used for testing the cargo bay shielding, since they won't deploy when they're shielded) and docking port when it detached (I had to sink the solar panels into the command pod itself to keep them intact), while Modular Rocket Systems's LAS shroud did not.  I might drop NecroBones a line to see if he made any adjustments on that point.

**Comment by sumghai** [comment]
> Bear in mind that AD 1.2.1 produces NullReferenceExceptions on parts that don't pass an animationName to the module -- I've made and PRed a fix at Starwaster/AnimatedDecouplers#3, and I'm happy to toss you a compiled DLL if you can't compile it yourself.

That would be very much appreciated, thanks :)

> (This fix doesn't touch the animation issue that Starwaster is working on.) 

Actually, turns out the animations not playing before decoupling was a PEBKAC on my part - I directly edited the Service Module and Avionics Ring CFGs on GitHub with **waitForAnimation = true** in September, but was testing an older local dev build last night without that added parameter. After syncing my local copy with the repo, the animate-before-decouple feature works just fine.

Sorry @Starwaster! I dun goofed :/

> Those NREs seem to cause issues with collision (fairings falling through parts) and staging (LES towers and integrated SRBs not firing, as you're seeing in #67), and my fix repairs both.

It does? Holy crap, I definitely need your DLL :)

> That said, it probably would be good for the colliders to get attention, since KSP 1.0.5 is redefining all colliders to be convex (in preparation for Unity 5 in 1.1, which does not support concave colliders on rigid bodies). I noticed that, when testing your BPC, it seemed to "rip off" the solar panels (used for testing the cargo bay shielding, since they won't deploy when they're shielded) and docking port when it detached (I had to sink the solar panels into the command pod itself to keep them intact), while Modular Rocket Systems's LAS shroud did not. I might drop NecroBones a line to see if he made any adjustments on that point.

Yes, the collider changes for 1.0.5/1.1 will still need to be done. It's going to be a bit of challenge, but I'm glad that at least we're now standardizing on convex colliders.

**Comment by Kerbas-ad-astra** [comment]
Yeah, KSP is pretty brittle in some ways -- I imagine that the NREs confuse the system as to which parts are shielded, and because shielded parts should not be staged or collide, this causes the staging and collision issues.

Here's a DLL for you: https://github.com/Kerbas-ad-astra/AnimatedDecouplers/releases/tag/v1.2.2-beta.1

**Comment by sumghai** [comment]
Okay, just tested the new DLL.

* Staging issues seem to be fixed now
 * BPC decoupler and jettison motors assigned to the same AG will both activate
 * SM decoupler and escape tower motors assigned to the same AG will both activate
* BPC and fairings are still snagging onto other parts, due to changes in concave collider behaviour; this I can (hopefully) fix.

Many thanks for helping me eliminate part of the problem :)

**Comment by sumghai** [comment]
Whoops, accidental closure.

**Comment by sumghai** [comment]
BPC colliders reworked, collider intersection and aero occlusion tests passed.

The BPC jettison rocket motors have a tendency to sometimes overheat and destroy the Mk1-2 Pod, ParaDock, Heatshield, Service Module or Avionics ring. The thermal properties of various parts may need to be adjusted to make them more resilient.

**Comment by sumghai** [comment]
All remaining part colliders have been updated as needed, and have passed all collision/occlusion tests.
