### ISSUE TITLE
BPC jettison motor exhaust overheating nearby parts

### ISSUE THREAD

**Issue by sumghai** [sumghai/SDHI_ServiceModuleSystem#69]
While verifying the new colliders for the Boost Protect Cover (BPC) in #66, it was found that the exhaust from the cover's integrated solid rocket jettison motors has a tendency to overheat and sometimes destroy nearby parts (such as the Service Module/Avionics Ring, the Mk1-2 Pod and surprisingly, the heatshield).

Ideally, the jettision motors should be tweaked to produce less heat, or the thermal properties of the cover itself adjusted to absorb as much heat as possible before any of it damages nearby parts (adjusting the thermal properties of other parts exposed to the exhaust is probably impractical).

EDIT: Relocating the thrustTransforms away from other parts is the best way to do this.

**TODO:**
 - [x] Finalize new location / orientation of thrustTransforms
 - [x] Add meshes and textures representing jettison motor exhaust
 - [x] Add AO bake to base BPC texture

**Comment by Kerbas-ad-astra** [comment]
Maybe canting/tilting the thrust transforms outward would prevent the exhaust from impinging on the other parts.

**Comment by sumghai** [comment]
I tilted the thrust transforms outward by 45 degrees.

When jettisoning the BPC during normal staging, the Service Module / Avionics Ring still explodes due to overheating.

When jettisoning the BPC after abort:
 - If the pod is moving at a constant velocity, the exhaust will safely miss the pod
 - If the pod is tumbling/wobbling mid-flight, the exhaust will damage/destroy the heat shield

A better solution may be to relocate the thrust transforms from the skirt of the BPC to somewhere in the middle or at the apex of the cover (i.e. as a "puller" rather than "pusher" jettison motor), and if necessary model/texture the exhaust ports / blisters.

**Comment by sumghai** [comment]
Relocating the thrust transforms a small distance up along the surface of the BPC (between the bottom of the skirt and the access hatch level) worked - no parts overheated even when the pod was tumbling/wobbling mid-flight.

Updated OP with TODO list.

**Comment by sumghai** [comment]
Tested OK, ready for V3.1.
